/* //device/libs/telephony/ril_commands.h
**
** Copyright 2006, The Android Open Source Project
** Copyright (C) 2012-2013 CYIT CO., LTD. All rights reserved.
**
** Licensed under the Apache License, Version 2.0 (the "License");
** you may not use this file except in compliance with the License.
** You may obtain a copy of the License at
**
**     http://www.apache.org/licenses/LICENSE-2.0
**
** Unless required by applicable law or agreed to in writing, software
** distributed under the License is distributed on an "AS IS" BASIS,
** WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
** See the License for the specific language governing permissions and
** limitations under the License.
*/
    {0, 0, NULL, NULL},                   //none
    {RIL_REQUEST_GET_SIM_STATUS, RIL_CHANNEL_OTHERS, dispatchVoid, responseSimStatus},
    {RIL_REQUEST_ENTER_SIM_PIN, RIL_CHANNEL_OTHERS, dispatchStrings, responseInts},
    {RIL_REQUEST_ENTER_SIM_PUK, RIL_CHANNEL_OTHERS, dispatchStrings, responseInts},
    {RIL_REQUEST_ENTER_SIM_PIN2, RIL_CHANNEL_OTHERS, dispatchStrings, responseInts},
    {RIL_REQUEST_ENTER_SIM_PUK2, RIL_CHANNEL_OTHERS, dispatchStrings, responseInts},
    {RIL_REQUEST_CHANGE_SIM_PIN, RIL_CHANNEL_OTHERS, dispatchStrings, responseInts},
    {RIL_REQUEST_CHANGE_SIM_PIN2, RIL_CHANNEL_OTHERS, dispatchStrings, responseInts},
    {RIL_REQUEST_ENTER_NETWORK_DEPERSONALIZATION, RIL_CHANNEL_OTHERS, dispatchDepersonalization, responseInts},
    {RIL_REQUEST_GET_CURRENT_CALLS, RIL_CHANNEL_VOICE, dispatchVoid, responseCallList},
    {RIL_REQUEST_DIAL, RIL_CHANNEL_VOICE, dispatchDial, responseVoid},
    {RIL_REQUEST_GET_IMSI, RIL_CHANNEL_OTHERS, dispatchVoid, responseString},
    {RIL_REQUEST_HANGUP, RIL_CHANNEL_VOICE, dispatchInts, responseVoid},
    {RIL_REQUEST_HANGUP_WAITING_OR_BACKGROUND, RIL_CHANNEL_VOICE, dispatchVoid, responseVoid},
    {RIL_REQUEST_HANGUP_FOREGROUND_RESUME_BACKGROUND, RIL_CHANNEL_VOICE, dispatchVoid, responseVoid},
    {RIL_REQUEST_SWITCH_WAITING_OR_HOLDING_AND_ACTIVE, RIL_CHANNEL_VOICE, dispatchVoid, responseVoid},
    {RIL_REQUEST_CONFERENCE, RIL_CHANNEL_VOICE, dispatchVoid, responseVoid},
    {RIL_REQUEST_UDUB, RIL_CHANNEL_VOICE, dispatchVoid, responseVoid},
    {RIL_REQUEST_LAST_CALL_FAIL_CAUSE, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_SIGNAL_STRENGTH, RIL_CHANNEL_OTHERS, dispatchVoid, responseRilSignalStrength},
    {RIL_REQUEST_VOICE_REGISTRATION_STATE, RIL_CHANNEL_NET, dispatchVoid, responseStrings},
    {RIL_REQUEST_DATA_REGISTRATION_STATE, RIL_CHANNEL_NET, dispatchVoid, responseStrings},
    {RIL_REQUEST_OPERATOR, RIL_CHANNEL_NET, dispatchVoid, responseStrings},
    {RIL_REQUEST_RADIO_POWER, RIL_CHANNEL_POWER, dispatchInts, responseVoid},// modify by CYIT 20120518 for fix radio power-off bug
    {RIL_REQUEST_DTMF, RIL_CHANNEL_VOICE, dispatchString, responseVoid},
    {RIL_REQUEST_SEND_SMS, RIL_CHANNEL_SMS, dispatchStrings, responseSMS},
    {RIL_REQUEST_SEND_SMS_EXPECT_MORE, RIL_CHANNEL_SMS, dispatchStrings, responseSMS},
    {RIL_REQUEST_SETUP_DATA_CALL, RIL_CHANNEL_PS, dispatchStrings, responseDataCallList},
    {RIL_REQUEST_SIM_IO, RIL_CHANNEL_SIMFILE, dispatchSIM_IO, responseSIM_IO},
    {RIL_REQUEST_SEND_USSD, RIL_CHANNEL_SS, dispatchUSSD, responseVoid},// modify by CYIT 20110819 for USSD
    {RIL_REQUEST_CANCEL_USSD, RIL_CHANNEL_SS, dispatchVoid, responseVoid},
    {RIL_REQUEST_GET_CLIR, RIL_CHANNEL_SS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_CLIR, RIL_CHANNEL_SS, dispatchInts, responseVoid},
    {RIL_REQUEST_QUERY_CALL_FORWARD_STATUS, RIL_CHANNEL_SS, dispatchCallForward, responseCallForwards},
    {RIL_REQUEST_SET_CALL_FORWARD, RIL_CHANNEL_SS, dispatchCallForward, responseVoid},
    {RIL_REQUEST_QUERY_CALL_WAITING, RIL_CHANNEL_SS, dispatchInts, responseInts},
    {RIL_REQUEST_SET_CALL_WAITING, RIL_CHANNEL_SS, dispatchInts, responseVoid},
    {RIL_REQUEST_SMS_ACKNOWLEDGE, RIL_CHANNEL_SMS, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_IMEI, RIL_CHANNEL_OTHERS, dispatchVoid, responseString},
    {RIL_REQUEST_GET_IMEISV, RIL_CHANNEL_OTHERS, dispatchVoid, responseString},
    {RIL_REQUEST_ANSWER, RIL_CHANNEL_VOICE, dispatchVoid, responseVoid},
    {RIL_REQUEST_DEACTIVATE_DATA_CALL, RIL_CHANNEL_PS, dispatchStrings, responseVoid},
    {RIL_REQUEST_QUERY_FACILITY_LOCK, RIL_CHANNEL_OTHERS, dispatchStrings, responseInts},
    {RIL_REQUEST_SET_FACILITY_LOCK, RIL_CHANNEL_OTHERS, dispatchStrings, responseInts},
    {RIL_REQUEST_CHANGE_BARRING_PASSWORD, RIL_CHANNEL_OTHERS, dispatchStrings, responseVoid},
    {RIL_REQUEST_QUERY_NETWORK_SELECTION_MODE, RIL_CHANNEL_NET, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_NETWORK_SELECTION_AUTOMATIC, RIL_CHANNEL_NET, dispatchVoid, responseVoid},
    {RIL_REQUEST_SET_NETWORK_SELECTION_MANUAL, RIL_CHANNEL_NET, dispatchString, responseVoid},
    {RIL_REQUEST_QUERY_AVAILABLE_NETWORKS, RIL_CHANNEL_NET, dispatchVoid, responseStrings},
    {RIL_REQUEST_DTMF_START, RIL_CHANNEL_VOICE, dispatchString, responseVoid},
    {RIL_REQUEST_DTMF_STOP, RIL_CHANNEL_VOICE, dispatchVoid, responseVoid},
    {RIL_REQUEST_BASEBAND_VERSION, RIL_CHANNEL_OTHERS, dispatchVoid, responseString},
    {RIL_REQUEST_SEPARATE_CONNECTION, RIL_CHANNEL_VOICE, dispatchInts, responseVoid},
    {RIL_REQUEST_SET_MUTE, RIL_CHANNEL_VOICE, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_MUTE, RIL_CHANNEL_VOICE, dispatchVoid, responseInts},
    {RIL_REQUEST_QUERY_CLIP, RIL_CHANNEL_SS, dispatchVoid, responseInts},
    {RIL_REQUEST_LAST_DATA_CALL_FAIL_CAUSE, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_DATA_CALL_LIST, RIL_CHANNEL_PS, dispatchVoid, responseDataCallList},
    {RIL_REQUEST_RESET_RADIO, RIL_CHANNEL_OTHERS, dispatchVoid, responseVoid},
    {RIL_REQUEST_OEM_HOOK_RAW, RIL_CHANNEL_OTHERS, dispatchRaw, responseRaw},
    {RIL_REQUEST_OEM_HOOK_STRINGS, RIL_CHANNEL_OTHERS, dispatchStrings, responseStrings},
    {RIL_REQUEST_SCREEN_STATE, RIL_CHANNEL_NET, dispatchInts, responseVoid},
    {RIL_REQUEST_SET_SUPP_SVC_NOTIFICATION, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_WRITE_SMS_TO_SIM, RIL_CHANNEL_SMS, dispatchSmsWrite, responseInts},
    {RIL_REQUEST_DELETE_SMS_ON_SIM, RIL_CHANNEL_SMS, dispatchInts, responseVoid},
    {RIL_REQUEST_SET_BAND_MODE, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_QUERY_AVAILABLE_BAND_MODE, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_STK_GET_PROFILE, RIL_CHANNEL_OTHERS, dispatchVoid, responseString},
    {RIL_REQUEST_STK_SET_PROFILE, RIL_CHANNEL_OTHERS, dispatchString, responseVoid},
    {RIL_REQUEST_STK_SEND_ENVELOPE_COMMAND, RIL_CHANNEL_OTHERS, dispatchString, responseString},
    {RIL_REQUEST_STK_SEND_TERMINAL_RESPONSE, RIL_CHANNEL_OTHERS, dispatchString, responseVoid},
    {RIL_REQUEST_STK_HANDLE_CALL_SETUP_REQUESTED_FROM_SIM, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_EXPLICIT_CALL_TRANSFER, RIL_CHANNEL_OTHERS, dispatchVoid, responseVoid},
    {RIL_REQUEST_SET_PREFERRED_NETWORK_TYPE, RIL_CHANNEL_NET, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_PREFERRED_NETWORK_TYPE, RIL_CHANNEL_NET, dispatchVoid, responseInts},
    {RIL_REQUEST_GET_NEIGHBORING_CELL_IDS, RIL_CHANNEL_OTHERS, dispatchVoid, responseCellList},
    {RIL_REQUEST_SET_LOCATION_UPDATES, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_CDMA_SET_SUBSCRIPTION_SOURCE, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_CDMA_SET_ROAMING_PREFERENCE, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_CDMA_QUERY_ROAMING_PREFERENCE, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_TTY_MODE, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_QUERY_TTY_MODE, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_CDMA_SET_PREFERRED_VOICE_PRIVACY_MODE, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_CDMA_QUERY_PREFERRED_VOICE_PRIVACY_MODE, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_CDMA_FLASH, RIL_CHANNEL_OTHERS, dispatchString, responseVoid},
    {RIL_REQUEST_CDMA_BURST_DTMF, RIL_CHANNEL_OTHERS, dispatchStrings, responseVoid},
    {RIL_REQUEST_CDMA_VALIDATE_AND_WRITE_AKEY, RIL_CHANNEL_OTHERS, dispatchString, responseVoid},
    {RIL_REQUEST_CDMA_SEND_SMS, RIL_CHANNEL_OTHERS, dispatchCdmaSms, responseSMS},
    {RIL_REQUEST_CDMA_SMS_ACKNOWLEDGE, RIL_CHANNEL_OTHERS, dispatchCdmaSmsAck, responseVoid},
    {RIL_REQUEST_GSM_GET_BROADCAST_SMS_CONFIG, RIL_CHANNEL_OTHERS, dispatchVoid, responseGsmBrSmsCnf},
    {RIL_REQUEST_GSM_SET_BROADCAST_SMS_CONFIG, RIL_CHANNEL_OTHERS, dispatchGsmBrSmsCnf, responseVoid},
    {RIL_REQUEST_GSM_SMS_BROADCAST_ACTIVATION, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_CDMA_GET_BROADCAST_SMS_CONFIG, RIL_CHANNEL_OTHERS, dispatchVoid, responseCdmaBrSmsCnf},
    {RIL_REQUEST_CDMA_SET_BROADCAST_SMS_CONFIG, RIL_CHANNEL_OTHERS, dispatchCdmaBrSmsCnf, responseVoid},
    {RIL_REQUEST_CDMA_SMS_BROADCAST_ACTIVATION, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_CDMA_SUBSCRIPTION, RIL_CHANNEL_OTHERS, dispatchVoid, responseStrings},
    {RIL_REQUEST_CDMA_WRITE_SMS_TO_RUIM, RIL_CHANNEL_OTHERS, dispatchRilCdmaSmsWriteArgs, responseInts},
    {RIL_REQUEST_CDMA_DELETE_SMS_ON_RUIM, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_DEVICE_IDENTITY, RIL_CHANNEL_OTHERS, dispatchVoid, responseStrings},
    {RIL_REQUEST_EXIT_EMERGENCY_CALLBACK_MODE, RIL_CHANNEL_OTHERS, dispatchVoid, responseVoid},
    {RIL_REQUEST_GET_SMSC_ADDRESS, RIL_CHANNEL_SMS, dispatchVoid, responseString},
    {RIL_REQUEST_SET_SMSC_ADDRESS, RIL_CHANNEL_SMS, dispatchString, responseVoid},
    {RIL_REQUEST_REPORT_SMS_MEMORY_STATUS, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_REPORT_STK_SERVICE_IS_RUNNING, RIL_CHANNEL_OTHERS, dispatchVoid, responseVoid},
    {RIL_REQUEST_CDMA_GET_SUBSCRIPTION_SOURCE, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_ISIM_AUTHENTICATION, RIL_CHANNEL_OTHERS, dispatchString, responseString},
    {RIL_REQUEST_ACKNOWLEDGE_INCOMING_GSM_SMS_WITH_PDU, RIL_CHANNEL_SMS, dispatchStrings, responseVoid},
    {RIL_REQUEST_STK_SEND_ENVELOPE_WITH_STATUS, RIL_CHANNEL_OTHERS, dispatchString, responseSIM_IO},
    {RIL_REQUEST_VOICE_RADIO_TECH, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_IMS_REGISTRATION_STATE, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_IMS_SEND_SMS, RIL_CHANNEL_OTHERS, dispatchImsSms, responseSMS},
    {RIL_REQUEST_GET_DATA_CALL_PROFILE, RIL_CHANNEL_OTHERS, dispatchInts, responseGetDataCallProfile},
    {RIL_REQUEST_SET_UICC_SUBSCRIPTION_SOURCE, RIL_CHANNEL_OTHERS, dispatchUiccSubscripton, responseVoid},
    {RIL_REQUEST_SET_DATA_SUBSCRIPTION_SOURCE, RIL_CHANNEL_OTHERS, dispatchVoid, responseVoid},
    {RIL_REQUEST_GET_UICC_SUBSCRIPTION_SOURCE, RIL_CHANNEL_OTHERS, dispatchVoid, responseUiccSubscription},
    {RIL_REQUEST_GET_DATA_SUBSCRIPTION_SOURCE, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_SUBSCRIPTION_MODE, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_TIME_REQUEST_INITAT, RIL_CHANNEL_OTHERS, dispatchTimeReq, responseVoid},//add by CYIT
    {RIL_TIME_REQUEST_CALL_STATE_CHANGED, RIL_CHANNEL_OTHERS, dispatchTimeReq, responseVoid},
    {RIL_TIME_REQUEST_POLL_SIM_STATE, RIL_CHANNEL_OTHERS, dispatchTimeReq, responseVoid},
    {RIL_TIME_REQUEST_DATA_CALL_LIST, RIL_CHANNEL_PS, dispatchTimeReq, responseVoid},
    {RIL_TIME_REQUEST_RELEASE_POWERLOCK, RIL_CHANNEL_OTHERS, dispatchTimeReq, responseVoid},
    {RIL_REQUEST_PLAY_TONE, RIL_CHANNEL_VOICE, dispatchInts, responseVoid},
    {RIL_REQUEST_SET_MO_TYPE, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_ATCTST_AUD, RIL_CHANNEL_OTHERS, dispatchRaw, responseRaw},
    {RIL_REQUEST_GET_SSWINFO, RIL_CHANNEL_OTHERS, dispatchVoid, responseStrings},
    {RIL_REQUEST_SELECT_PB_EF, RIL_CHANNEL_PB, dispatchStrings, responseVoid},
    {RIL_REQUEST_WRITE_PB_RECORD, RIL_CHANNEL_PB, dispatchStrings, responseVoid},
    {RIL_REQUEST_WRITE_PB_RECORD_USER_DEFINED, RIL_CHANNEL_PB, dispatchStrings, responseVoid},
    {RIL_REQUEST_READ_PB_RECORD_USER_DEFINED, RIL_CHANNEL_PB, dispatchInts, responseReadPbRec},
    {RIL_REQUEST_GET_PB_RECORD_SIZE, RIL_CHANNEL_PB, dispatchVoid, responseInts},
    {RIL_REQUEST_GET_PB_CONTENT_LENGTH, RIL_CHANNEL_PB, dispatchVoid, responseInts},
    {RIL_REQUEST_QUERY_CALL_RESTRICT_STATUS, RIL_CHANNEL_OTHERS, dispatchStrings, responseInts},
    {RIL_REQUEST_SET_CALL_RESTRICT_STATUS, RIL_CHANNEL_OTHERS, dispatchStrings, responseVoid},
    {RIL_REQUEST_SET_SMS_STORAGE_LOC, RIL_CHANNEL_SMS, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_SMS_STORAGE_STATE, RIL_CHANNEL_SMS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_TE_TYPE, RIL_CHANNEL_NET, dispatchString, responseVoid},
    {RIL_REQUEST_GET_TE_TYPE, RIL_CHANNEL_NET, dispatchVoid, responseString},
    {RIL_REQUEST_SET_UE_CATEGORY, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_UE_CATEGORY, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_GET_PS_ATTACHED, RIL_CHANNEL_PS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_PS_ATTACHED, RIL_CHANNEL_PS, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_TD_FRQ_LOCK, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_TD_FRQ_LOCK, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_TD_CELL_ID_LOCK, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_TD_CELL_ID_LOCK, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_GSM_FRQ_LOCK, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_GSM_FRQ_LOCK, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_PRO_VERSION, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_PRO_VERSION, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_APN_INFO, RIL_CHANNEL_PS, dispatchVoid, responseApnInfo},
    {RIL_REQUEST_SET_APN_INFO, RIL_CHANNEL_PS, dispatchApnInfo, responseVoid},
    {RIL_REQUEST_GET_PDP_ACTIVE, RIL_CHANNEL_PS, dispatchVoid, responsePdpInfo},
    {RIL_REQUEST_SET_PDP_ACTIVE, RIL_CHANNEL_PS, dispatchInts, responseString},
    {RIL_REQUEST_GET_PDP_QOS, RIL_CHANNEL_PS, dispatchVoid, responseQosInfo},
    {RIL_REQUEST_SET_PDP_QOS, RIL_CHANNEL_PS, dispatchInts, responseVoid},
    {RIL_REQUEST_SET_TD_FRQ_UNLOCK, RIL_CHANNEL_OTHERS, dispatchVoid, responseVoid},
    {RIL_REQUEST_SET_TD_CELL_UNLOCK, RIL_CHANNEL_OTHERS, dispatchVoid, responseVoid},
    {RIL_REQUEST_GET_POWER_SAVING_CTRL, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_POWER_SAVING_CTRL, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_ENTER_BIOS, RIL_CHANNEL_OTHERS, dispatchVoid, responseVoid},
    {RIL_REQUEST_GET_LOG_CTRL, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_LOG_CTRL, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_USB_ENUM_CTRL, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_USB_ENUM_CTRL, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_RESET_FLAG_CTRL, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_RESET_FLAG_CTRL, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_VERSION_CTRL, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_VERSION_CTRL, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_SET_2NDPDP_CONTEXT, RIL_CHANNEL_PS, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_CELL_INFO, RIL_CHANNEL_OTHERS, dispatchVoid, responseCellInfo},
    {RIL_REQUEST_GET_PREFER_NETLIST, RIL_CHANNEL_NET, dispatchVoid, responsePrenet},
    {RIL_REQUEST_SET_PREFER_NETLIST, RIL_CHANNEL_NET, dispatchStrings, responseVoid},
    {RIL_REQUEST_GET_POWERON_ATTACH_MODE, RIL_CHANNEL_NET, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_POWERON_ATTACH_MODE, RIL_CHANNEL_NET, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_POWERON_NETWORKSEL_CTRL, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_POWERON_NETWORKSEL_CTRL, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_STOP_PDPDATA_CTRL, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_STOP_PDPDATA_CTRL, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_IP_CHECK_CTRL, RIL_CHANNEL_OTHERS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_IP_CHECK_CTRL, RIL_CHANNEL_OTHERS, dispatchInts, responseVoid},
    {RIL_REQUEST_GET_SMS_BEAR_CTRL, RIL_CHANNEL_SMS, dispatchVoid, responseInts},
    {RIL_REQUEST_SET_SMS_BEAR_CTRL, RIL_CHANNEL_SMS, dispatchInts, responseVoid},
    {RIL_REQUEST_CHANGE_VOLUME,RIL_CHANNEL_VOICE,dispatchInts,responseVoid},
    {RIL_REQUEST_CHOSE_VOICE_PATH,RIL_CHANNEL_VOICE,dispatchInts,responseVoid},
    {RIL_REQUEST_SET_CALL_RECORDING,RIL_CHANNEL_VOICE,dispatchInts,responseVoid},
    {RIL_REQUEST_QUERY_NETWORKS_WITH_TYPE, RIL_CHANNEL_NET, dispatchVoid, responseStrings},
    {RIL_REQUEST_GET_SIM_PIN_PUK_REMAIN_COUNT,RIL_CHANNEL_OTHERS,dispatchInts,responseInts}
